version: "3.1"
services:
  db:
    container_name: transbase
    image: registry.transaction.de:5050/containers/transbase:8.5.1_alpine-3.16
    ports:
      - "2024:2024"
    environment:
      TRANSBASE_PASSWORD: transbase
    secrets:
      - license
    volumes:
      - db:/data/transbase
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:

secrets:
  license:
    file: tblic.ini
