spring:
  datasource:
    url: jdbc:transbase://localhost:2024/cashbook
    driver-class-name: transbase.jdbc.Driver
    username: tbadmin
    password: transbase
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: de.transaction.demo.hibernate.TransbaseDialect
        format_sql: true
    show-sql: true
